# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/shortlink
      - REDIS_HOST=redis        # this is the service name
      - REDIS_PORT=6379
      - ALLOWED_ORIGINS=http://localhost:8080,http://localhost:3000,http://localhost:4000
    volumes:
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./enforce-pnpm.js:/app/enforce-pnpm.js
    depends_on:
      - mongo
      - redis
    command: pnpm dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:4000/api
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/pnpm-lock.yaml:/app/pnpm-lock.yaml
    command: pnpm dev --host

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

networks:
  default:
    name: url-shortener-net
